### ISSUE TITLE
Feeds not always fetching

### ISSUE THREAD

**Issue by lordmatt** [cuny-academic-commons/external-group-blogs#1]
I've looked at the code and it looks like it should wor. However, for my site, nothing short of "updating" the RSS feeds works in pulling the feed.

**Comment by lordmatt** [comment]
I figured it just needed a hook into the cron but while trying to figure that out I found it already had one. I assume this is the code that CBox uses?

**Comment by boonebgorges** [comment]
Yes, cron is used to trigger background updates. See https://github.com/cuny-academic-commons/external-group-blogs/blob/master/includes/bp-groups-externalblogs.php#L406

**Comment by lordmatt** [comment]
That's what I thought. Strange. I'll go take another look at my server setup.
