### ISSUE TITLE
This code appears redundant

### ISSUE THREAD

**Issue by lordmatt** [cuny-academic-commons/external-group-blogs#10]
In bp_groupblogs_fetch_group_feeds I found this

```
			try { $rss = new SimpleXmlElement( $test['body'] ); }
			catch( Exception $e ){
				continue;
			}

			$rss = fetch_feed( trim( $feed_url ) );
```

I'm not clear what the try/catch is doing as it instantly rewrites the var with fetch_feed.

**Comment by lordmatt** [comment]
I commented it out and the code seems to work better for it.

**Comment by boonebgorges** [comment]
Good catch. It's not clear to me how it ended up there in the first place. I've removed it.
