### ISSUE TITLE
Automated updates from feeds?

### ISSUE THREAD

**Issue by lordmatt** [cuny-academic-commons/external-group-blogs#7]
Currently, feeds only update when the group has user activity. Is there a chron or other trigger that can be used to automatically update groups with external blog feeds?

**Comment by boonebgorges** [comment]
The plugin ought to run its checks on a cron job. See https://github.com/cuny-academic-commons/external-group-blogs/blob/6146a749b546dadcaff47a7317ad4f796dfabdb9/loader.php#L35, https://github.com/cuny-academic-commons/external-group-blogs/blob/6146a749b546dadcaff47a7317ad4f796dfabdb9/includes/bp-groups-externalblogs.php#L408 So, by default, it should run checks hourly for all groups. (The check also runs each hour that the group is visited. See https://github.com/cuny-academic-commons/external-group-blogs/blob/6146a749b546dadcaff47a7317ad4f796dfabdb9/includes/bp-groups-externalblogs.php#L363)

If the cron job is not working, you should first see whether it's scheduled on your site. A tool like https://wordpress.org/plugins/wp-crontrol/ should help. Look for 'bp_groupblogs_cron'.

**Comment by lordmatt** [comment]
You are right. This was not an external blogs issue. It was a wp_cron not running properly issue.
